SELECT
  anno,
  regione,
  atc1,
  descrizione_atc1,
  SUM(spesa_convenzionata + spesa_flusso_tracciabilita) AS spesa_totale
FROM (
  SELECT * FROM `analisi-clinica-su-bigquery.DATASET_AIFA_CONSUMO_FARMACI_2016_2023.DATASET_AIFA_CONSUMO_FARMACI_2016`
  UNION ALL
  SELECT * FROM `analisi-clinica-su-bigquery.DATASET_AIFA_CONSUMO_FARMACI_2016_2023.DATASET_AIFA_CONSUMO_FARMACI_2017`
  UNION ALL
  SELECT * FROM `analisi-clinica-su-bigquery.DATASET_AIFA_CONSUMO_FARMACI_2016_2023.DATASET_AIFA_CONSUMO_FARMACI_2018`
  UNION ALL
  SELECT * FROM `analisi-clinica-su-bigquery.DATASET_AIFA_CONSUMO_FARMACI_2016_2023.DATASET_AIFA_CONSUMO_FARMACI_2019`
  UNION ALL
  SELECT * FROM `analisi-clinica-su-bigquery.DATASET_AIFA_CONSUMO_FARMACI_2016_2023.DATASET_AIFA_CONSUMO_FARMACI_2020`
  UNION ALL
  SELECT * FROM `analisi-clinica-su-bigquery.DATASET_AIFA_CONSUMO_FARMACI_2016_2023.DATASET_AIFA_CONSUMO_FARMACI_2021`
  UNION ALL
  SELECT * FROM `analisi-clinica-su-bigquery.DATASET_AIFA_CONSUMO_FARMACI_2016_2023.DATASET_AIFA_CONSUMO_FARMACI_2022`
  UNION ALL
  SELECT * FROM `analisi-clinica-su-bigquery.DATASET_AIFA_CONSUMO_FARMACI_2016_2023.DATASET_AIFA_CONSUMO_FARMACI_2023`
)
GROUP BY anno, regione, atc1, descrizione_atc1
ORDER BY anno, regione, spesa_totale DESC;

